package com.book.service.system.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.experimental.FieldNameConstants;

import java.math.BigDecimal;

@DynamoDBTable(tableName = "BOOK")
@Data
@FieldNameConstants
public class Book {
    @DynamoDBHashKey(attributeName = "BOOK_ID")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "TITLE")
    private String title;

    @DynamoDBAttribute(attributeName = "CATEGORY")
    private String category;

    @DynamoDBAttribute(attributeName = "PRICE")
    private BigDecimal price;

    @DynamoDBAttribute(attributeName = "AUTHOR")
    private String author;

    @DynamoDBAttribute(attributeName = "PUBLISHER")
    private String publisher;
}
